### ISSUE TITLE
[Common Issue] Chest Tracker Mod client issue

### ISSUE THREAD

**Issue by KleinDevDE** [Legoman99573/GravesX#27]
### Minecraft Server Version

1.21.1

### `/graves dump` output

https://mclo.gs/oRx8z2V

### Summary of the bug

After the latest update to 4.9.4.1,

The first hologram contains the texts I have set.
The second hologram only contains “KleinDev's Grave”, which is (usually) only created/spawned when you have emptied the grave.

I have also stopped the server, deleted the GravesX folder and started it again.
The problem is still occuring, so it's not a configuration problem.

I also created a fresh local PaperMC Server and joined them with the default Vanilla 1.21.1 Client (from the Minecraft Launcher).
The same problem is still happening.-

### Steps to Reproduce

1. die
2. Empty your skull (right click, loot all items)
3. Skull got removed, the HUD also, but then another HUD got created

### Expected Result

After looting the grave, the grave and it's Holographs are removed completely.

### Actual Result

After looting the grave, the grave and it's Holographs is removed,
but a new Holographic with the text "KleinDev's Grave" has spawned.
You can only remove it by placing another block to the position, where the skull was, and then remove the block.

### Screenshots

![image](https://github.com/user-attachments/assets/e781f4fc-4383-4cc9-a263-f8952a6edc80)
![image](https://github.com/user-attachments/assets/d50d2d45-1c24-46cf-9c25-b0388b0c838b)
![image](https://github.com/user-attachments/assets/86413cdc-4094-425b-9162-2b8b54b73f28)
![image](https://github.com/user-attachments/assets/bb3ae5e8-0477-49da-ae85-532e3cdaf5ec)

### Version Confirmation

- [X] I confirm that the issue is present in the latest GravesX Spigot Release or Development Builds.
- [X] If I use development builds in a production environment, I am aware that I will not receive support if I lose data.
- [X] If the issue is caused by another fork or Graves 4.9, then I expect to not get support here and my issue will be closed.
- [X] I am not running an outdated version of GravesX when reporting
- [ ] I am not just clicking checkboxes randomly without reading them. If I don't check this, then I did read everything.

**Comment by Legoman99573** [comment]
Likely has to do with the validation to make sure grave holograms are removed when armor stand ticks are set to true. Will check this afternoon.

**Comment by KleinDevDE** [comment]
After some investigation, I found out that this was only client-side.  
The reason for this behaviour was the Mod [Chest Tracker](https://modrinth.com/mod/chest-tracker) and it's feature:  
_Displays custom names of containers in the world (can be disabled under the Memory Bank Settings)._  

@Legoman99573 This issue can be closed now
I for myself leave this issue open to make sure, that you read this before making extra investigations.
P.S.: ty for the "good first issue" label 😄 

---

### To all other users having the same problem
You can disable this feature in the Mod settings.  
![image](https://github.com/user-attachments/assets/ce07a0ed-7939-4add-a64c-df3d72df0412)
-> Maybe you need to install the [ModMenu](https://modrinth.com/mod/modmenu) first.

**Comment by Legoman99573** [comment]
Pinned for future reference
